spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recipe_discovery?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 01218923570Aa

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

  thymeleaf:
    cache: false

  # ✅ GMAIL SMTP (gửi email thông báo)
  mail:
    host: smtp.gmail.com
    port: 587
    username: thaibao9714@gmail.com
    password: dhiopbbqyfdmoazw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

# ✅ App config riêng cho link trong email
app:
  base-url: "http://localhost:8080"

# (tuỳ chọn) log để debug gửi mail / scheduler
logging:
  level:
    org.springframework.mail: INFO
    org.springframework.scheduling: INFO
